version: '3.7'

# We are going to build a Docker container for Hugo that just contains the Go OS at this stage.  The Dockerfile will need to be created to hold the installation.
services:
  hugo:
    container_name: hugo
    image: golang:1.22-alpine
    platform: linux/arm/v7 # Specifies the platform architecture for the container
    volumes:
     - type: volume
       source: nas-hugo
       target: /src
    networks:
      - hugo_network
    ports:
      - "$HUGO_PORT_DEFAULT:$HUGO_PORT_EXTERNAL"
    
volumes:
  nas-hugo:
    driver_opts:
      type: nfs
      o: "addr=nas-home.local,rw,nfsvers=4"
      device: :/volume1/hs_esphome/

# Network configuration section for defining how services will communicate internally
networks:
  hugo_network:
    driver: bridge # Uses a bridge network for inter-service communication
