version: '3.7'

# We are going to build a Docker container for Hugo that just contains the Go OS at this stage.  The Dockerfile will need to be created to hold the installation.
services:
  hugo:
    container_name: hugo
    image: golang:1.22-alpine
    platform: linux/arm/v7 # Specifies the platform architecture for the container
    dns:
      - 192.168.1.1
      - 172.64.36.1
    volumes:
     - type: volume
       source: nas-hugo-vol
       target: /srv/hs_hugo
    networks:
      - hugo_network
    ports:
      - "$HUGO_PORT_DEFAULT:$HUGO_PORT_EXTERNAL"
    command: >
      sh -c "apk add --no-cache hugo &&
             cd /srv/hs_hugo &&
             hugo server --bind 0.0.0.0 --port 1313"    
volumes:
  nas-hugo-vol:
    driver_opts:
      type: nfs
      o: "addr=nas-home.local,rw,nfsvers=4,soft,timeo=30,retrans=3"
      device: :/volume1/hs_hugo/

# Network configuration section for defining how services will communicate internally
networks:
  hugo_network:
    driver: bridge # Uses a bridge network for inter-service communication
