version: "3.9"

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - '$OPENWEBUI_PORT:8080'
    environment:
      - TZ=Europe/London
      - OPENWEBUI_SECRET_KEY=changeme_please_secure
    volumes:
     - type: volume
       source: nas-openweb-ui
       target: /app/backend/data # Mounts a volume for persistent storage of data
       
    networks:
      - default
    dns:
      - 192.168.1.1 # internal DNS server to resolve for .lan network

volumes:
  nas-openweb-ui:
    driver_opts:
      type: nfs
      o: "addr=nas-home.lan,rw,nfsvers=4"
      device: :/volume1/hs_openwebui
  
networks:
  default:
    name: openwebui_network
