version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    entrypoint: /bin/sh
    command: -c '
      ollama serve & 
      sleep 2 && 
      ollama pull mistral && 
      ollama pull llama3 && 
      wait' 
    ports:
      - "11434:11434"  # Optional for debugging
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - nginx_network

volumes:
  ollama_data:

networks:
  nginx_network:
    external: true
