version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: >
      ollama serve & 
      sleep 2 && 
      ollama pull mistral && 
      ollama pull llama3 && 
      wait
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - nginx_network
    ports:
      - "11434:11434"  # Optional for debugging

volumes:
  ollama_data:

networks:
  nginx_network:
    external: true
