version: "3.7" # Specifies the version of the Docker Compose file format

# This section defines all the services that make up the application stack for nginx
services:
  # Main application service configuration
  esphome:
    container_name: esphome # Unique identifier for this container to distinguish it from others
    image: esphome/esphome:latest
    platform: linux/x86_64
    restart: unless-stopped # Policy that determines the restart behavior, here set to only stop manually
    volumes:
     - type: volume
       source: nas-esphome
       target: /config
    network-mode: host # Uses the host's network stack, allowing direct access to host ports
    ports:
     - '$ESPHOME_PORT_EXTERNAL:$ESPHOME_PORT_DEFAULT'
    environment:
     - TZ=Europe/London

volumes:
#  esphome_config: # Store for espHome configuration files
  nas-esphome:
    driver_opts:
      type: nfs
      o: "addr=nas-home.local,rw,nfsvers=4"
      device: :/volume1/hs_esphome
